--yyyy-mm-dd
SELECT TOP 3 CONVERT(VARCHAR, DATE, 23)
FROM TIME_TABLE

--yyyy/mm/dd
SELECT TOP 3 CONVERT(VARCHAR, DATE, 111)
FROM TIME_TABLE

--yyyymmdd
SELECT TOP 3 CONVERT(VARCHAR, DATE, 112)
FROM TIME_TABLE

--yyyy.mm.dd
SELECT TOP 3 CONVERT(VARCHAR, DATE, 102)
FROM TIME_TABLE
