--Use with GROUP BY
SELECT COL1, COL2, SUM(VAL1) OVER(PARTITION BY COL1) FROM TABLE
GROUP BY COL1, COL2 --GROUP BY here is for distinct, but not for aggregation.

--Use with PARTITION BY and ORDER BY 
SELECT COL1, COL2, 
  SUM(VAL1) OVER(PARTITION BY COL1) QTY,
  SUM(VAL1) OVER(ORDER BY COL1) ACCU_QTY,
  SUM(VAL1) OVER() TOTAL_QTY,
FROM TABLE
